const http=require('http'),fs=require('fs'),path=require('path');
for(const line of fs.readFileSync(path.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^\s*([^#=]+)=(.*)$/);if(m&&!process.env[m[1].trim()])process.env[m[1].trim()]=m[2].trim().replace(/^['"]|['"]$/g,'')}
const unavailable='Not available in the documents.';
const docs=['vehicle-safety-and-maintenance-reference.md','general-manufacturing-quality-standard.md'].map(name=>({name,text:fs.readFileSync(path.join(__dirname,'rag_seed_documents',name),'utf8')}));
function answer(question){const q=String(question||'').toLowerCase();if(/\b(emergency|injury|injured|bleeding|unconscious|imminent danger|fire|gas leak)\b/.test(q))return {state:'escalate',answer:'Stop work if safe and follow the configured site emergency and safety escalation process.',citations:[]};const terms=q.match(/[a-z]{4,}/g)||[];const found=docs.map(d=>({d,score:terms.filter(t=>d.text.toLowerCase().includes(t)).length})).sort((a,b)=>b.score-a.score)[0];if(!found||found.score===0)return {state:'insufficient_evidence',answer:unavailable,citations:[]};const lines=found.d.text.split('\n').filter(x=>x.trim());const excerpt=lines.find(x=>terms.some(t=>x.toLowerCase().includes(t)))||lines[0];return {state:'grounded_answer',answer:`The approved reference states: ${excerpt.replace(/^[-#0-9. ]+/,'')} [S1]`,citations:[{title:found.d.name.replace('.md','').replaceAll('-',' '),section:'Retrieved reference',excerpt,source_url:`/source/${found.d.name}`}]};}
async function generate(question,result){if(result.state!=='grounded_answer'||!process.env.GEMINI_API_KEY)return result;const source=docs.find(d=>d.name.replace('.md','').replaceAll('-',' ')===result.citations[0].title)?.text||result.citations[0].excerpt;const prompt=`You are a floor-supervisor document assistant. Answer the question clearly in 2-5 sentences using ONLY the evidence below. Do not use outside knowledge. Cite every factual sentence with [S1]. If evidence is insufficient, respond exactly: ${unavailable}\n\nQuestion: ${question}\n\nEvidence [S1]:\n${source.slice(0,12000)}`;try{const model=process.env.GEMINI_MODEL||'gemini-2.5-flash-lite';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.1,maxOutputTokens:400}})});const data=await r.json();const text=data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();if(text&&text.includes('[S1]'))return {...result,answer:text};return result}catch{return result}}
const html=`<!doctype html><title>Supervisor Document Assistant</title><style>body{font:16px system-ui;max-width:760px;margin:40px auto;padding:0 16px}textarea,button{font:inherit;padding:10px}textarea{width:100%;box-sizing:border-box}article{border:1px solid #ddd;padding:16px;margin-top:16px}details{margin-top:8px}</style><h1>Supervisor Document Assistant</h1><p>Answers are limited to the local approved demo corpus.</p><textarea id=q rows=3 placeholder="Ask about safety, maintenance, or quality..."></textarea><p><button id=b>Ask</button></p><main id=o></main><script>const q=document.querySelector('#q'),o=document.querySelector('#o');document.querySelector('#b').onclick=async()=>{o.textContent='Searching approved documents...';let r=await fetch('/query',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q.value})});let x=await r.json();o.innerHTML='<article><p>'+x.answer.replaceAll('<','&lt;')+'</p>'+x.citations.map(c=>'<details><summary>'+c.title+'</summary><p>'+c.excerpt+'</p></details>').join('')+'</article>'}</script>`;
function handler(req,res){if(req.url==='/'||req.url==='/index.html'){res.writeHead(200,{'content-type':'text/html'});return res.end(html)}if(req.url==='/query'&&req.method==='POST'){let b='';req.on('data',x=>b+=x);return req.on('end',async()=>{let x={};try{x=JSON.parse(b)}catch{}res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(await generate(x.question,answer(x.question))))})}if(req.url.startsWith('/source/')){const n=path.basename(req.url);const f=path.join(__dirname,'rag_seed_documents',n);if(fs.existsSync(f)){res.writeHead(200,{'content-type':'text/plain'});return res.end(fs.readFileSync(f))}}res.writeHead(404);res.end('Not found')}
if(require.main===module)http.createServer(handler).listen(process.env.PORT||3000,()=>console.log('http://localhost:'+(process.env.PORT||3000)));module.exports={answer,handler};
